author: TomyLobo
description: Allows creating horse/boat/dragon routes
main: eu.tomylobo.routes.BukkitRoutes
name: routes
url: https://github.com/TomyLobo/routes
version: 'maven-version-number'

commands:
  routes:
    aliases: [ro]
  travel:
    aliases: [tr]
